name: test core

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: download test file
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://raw.githubusercontent.com/jar-analyzer/test/refs/heads/main/javasec-1.15.jar -O javasec-1.15.jar
          wget https://github.com/4ra1n/test-springboot/releases/download/0.0.1/test-0.0.1-SNAPSHOT.jar -O test-0.0.1-SNAPSHOT.jar
      - name: run maven core test
        run: mvn test -Dtest=SpringCoreTest#testRun
      - name: run maven custom test
        run: mvn test -Dtest=SpringCustomTest#testRun
      - name: clean test file
        run: rm -f javasec-1.15.jar && rm -rf test-0.0.1-SNAPSHOT.jar